"""
Generated Pydantic models for AMIS components.

AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!

This file was automatically generated from the AMIS JSON Schema.
To regenerate, run: python scripts/generate_models.py

Generation info:
- Generated at: 2025-12-30T00:41:35.693664
- Source schema: schema_simplified.json
- Generator: datamodel-code-generator

For more information about AMIS, visit: https://github.com/baidu/amis
"""

# generated by datamodel-codegen:
#   filename:  schema_simplified.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class LoadingConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    root: dict[str, Any] | None = None
    show: dict[str, Any] | None = None


class AsidePosition(Enum):
    left = 'left'
    right = 'right'


class Messages(BaseModel):
    """
    AMIS Messages component.
    """